### ISSUE TITLE
Link to Antidote not quite works

### ISSUE THREAD

**Issue by qrilka** [bieniusa/antidote-haskell-client#1]
Hello @bieniusa 
On your university page https://softech.cs.uni-kl.de/homepage/de/staff/AnnetteBieniusa/ I see a link to https://antidotedb.org/ which gives ERR_TIMED_OUT but without `https` it redirects to http://syncfree.github.io/antidote/ probably it's time to fix the link?

**Comment by bieniusa** [comment]
Thank you very much!! I fixed it :)
